# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Take App Store screenshots on all required simulators"
  lane :screenshots do
    # Boot simulators and seed sample photos before running tests
    ["iPhone 17 Pro Max", "iPhone 16e"].each do |device|
      sh "xcrun simctl boot '#{device}' 2>/dev/null; true"
      Dir["fastlane/screenshots/assets/*.jpg"].each do |photo|
        sh "xcrun simctl addmedia '#{device}' '#{File.expand_path(photo)}'"
      end
    end

    snapshot
  end

end
